Solana integration for wallet monitor
XLabs/wallet-monitor pull request #3
Opened 2023-03-29 17:18 UTC by CiottiGiorgio

Might be some more things to fix but it's in a usable stage. Could be a good time to consider integration with gzim engine.

2023-03-29 21:59 UTC, solanoepalacio requested changes

2023-03-29 21:59 UTC, solanoepalacio commented on src/wallets/solana/index.ts
> +    if (!this.options.nodeUrl)
I think it would be better to add a type to the defaultConfigs in solana so that we make sure that we never commit a network without a default nodeUrl instead of doing a runtime check. Would you agree?

2023-03-29 21:59 UTC, solanoepalacio commented on src/wallets/solana/index.ts
> +      tokenBalancesDistinct.set(mintAccount, (tokenBalancesDistinct.get(mintAccount) ?? 0) + tokenAccountBalance)
Is it possible to get two times the same `mintAccount`? this would be equivalent of having two types of USDC for the same wallet?

2023-03-29 21:59 UTC, solanoepalacio commented on src/wallets/solana/index.ts
> +      this.tokenData[token] = await getMint(this.connection, new PublicKey(token))
I think we should map the result of `getMint` before storing it into the tokenData map so that in the future we have a clear idea on what properties `tokenData` without having to run the code.
I mean something line:
```
const mint = await getMint(...);
this.tokenData[token] = { something: mint.something };
```

2023-03-29 21:59 UTC, solanoepalacio commented on src/wallets/solana/index.ts
> +        symbol: 'unknown',
any chance we use a map in the config with the most common tokens to get their symbols? otherwise this is rendered kind of useless...
Imagine the case you are monitoring a few tokens in the solana chain, then in the result you will get balances, but you won't know what tokens they belong to :shrug:

2023-03-29 21:59 UTC, solanoepalacio commented on src/wallets/solana/index.ts
> +  tokenPollConcurrency?: number;
I think in Solana we don't need this option since balances are polled in a single request, we better remove it

2023-03-29 21:59 UTC, solanoepalacio commented on src/wallets/solana/index.ts
> +        symbol: 'unknown',
in the wallet-monitor example, we are actually receiving the `USDC` symbol to get the token balance, and then we return `unknown` as the symbol, which might feel confusing...

maybe In the cases in which is not possible to get the symbol we should at least return the tokenAddress so that at least there is a way to know what token the balance is for :thinking:

2023-03-29 22:10 UTC, CiottiGiorgio commented on src/wallets/solana/index.ts
> +      this.tokenData[token] = await getMint(this.connection, new PublicKey(token))
For web3.js I find that the return type is obscure most times on the docs.
For that particular function (which comes from spl-token sdk), [the docs](https://solana-labs.github.io/solana-program-library/token/js/interfaces/Mint.html) are extremely so I wouldn't personally do that but I can see how in some conditions it could be helpful.

2023-03-29 22:16 UTC, CiottiGiorgio commented on src/wallets/solana/index.ts
> +      tokenBalancesDistinct.set(mintAccount, (tokenBalancesDistinct.get(mintAccount) ?? 0) + tokenAccountBalance)
So the matter is kinda complicated but essentially there are three elements at play:
- SPL Token Program (think of this like the ERC20 standard but as an on-chain contract/program)
- Mint Account (the actual implementation of a token following the standard of the Token Program)
- Token Account (this is the account owned in a non-strict sense by the Mint Account and the user account used to represent the actual users' balance for that particular Token)

It is possible that for a pair (mint account, user account), there are multiple Token Accounts holding data such as the user's balance.

This is at least my limited understanding on the matter. Tagging @nonergodic for confirmation

2023-03-29 22:18 UTC, CiottiGiorgio commented on src/wallets/solana/index.ts
> +        symbol: 'unknown',
Ah yes absolutely I forgot to implement the part where we fallback to known tokens if we don't have the symbol in the return data.
Will do that absolutely

2023-03-29 22:21 UTC, CiottiGiorgio commented on src/wallets/solana/index.ts
> +  tokenPollConcurrency?: number;
Yes the only place where this should be used (but it's currently not because I forgot) is in the warmup phase where info about tokens are polled separately.

That's a one time execution each time the monitor is started. I don't know, potentially we want to keep this in because the same process could be restarted multiple times leading to a saturation of the quotas? Long shot?

2023-03-30 16:22 UTC, solanoepalacio commented on src/wallets/solana/index.ts
> +    if (!this.options.nodeUrl)
Actually what I mean is that if we type the default-config and make nodeUrl not optional, then if the user of the lib didn't provide a nodeUrl in the config, we are sure that we got one from the default-config,
So esentially it would be typing the variable `SOLANA_DEFAULT_CONFIGS`
Something like this (I made the example for ethereum):
![image](https://user-images.githubusercontent.com/12457451/228901314-b1566d84-f6be-46e5-a154-3da7e04cd72a.png)

2023-03-30 16:23 UTC, solanoepalacio commented on src/wallets/solana/index.ts
> +    if (!this.options.nodeUrl)
What I mean is that we can be sure that `this.options.nodeUrl` has a value because on line 60 you merged the user options with the default options

2023-03-30 16:25 UTC, solanoepalacio commented on src/wallets/solana/index.ts
> +        symbol: 'unknown',
thanks :raised_hands:

2023-03-30 17:42 UTC, CiottiGiorgio commented on src/wallets/solana/index.ts
> +    if (!this.options.nodeUrl)
Ah ok I understand. I think that two relevant things are at play here:
- The rightmost spread object (`...options`)  does contain an optional field `nodeUrl?` and therefore what I think is happening is that TS cannot always correctly infer that `nodeUrl` from `...defaultOptions` will not be overwritten by the possible `undefined` in `options.nodeUrl`. [Relevant StackOverflow](https://stackoverflow.com/questions/60626844/spread-operator-and-optional-fields-how-to-infer-proper-type)
- Ethereum provider actually takes an optional `url` argument. This could be the reason that the compiler is not firing off warnings.

Solana `Connection` on the other hand takes a required `endpoint` argument so that's why I'm being very explicit in convincing the compiler that that field is indeed going to be there.
I'll write this quirk in the code as a comment.

2023-03-30 18:35 UTC, CiottiGiorgio commented on src/wallets/solana/index.ts
> +        symbol: 'unknown',
This is addressed by the latest commits

2023-03-30 20:17 UTC, solanoepalacio approved these changes

2023-03-30 20:36 UTC, merged